# fly.toml app configuration file generated for odduck on 2024-05-27T11:45:25+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'odduck'
primary_region = 'ams'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
